### ISSUE TITLE
Make head branch name configurable

### ISSUE THREAD

**Issue by kamatama41** [at-wat/assets-sync-action#18]
We have multiple asset sync actions on one job like following.

```yaml
name: assets-sync
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync general assets
        uses: at-wat/assets-sync-action@v0
        with:
          root_dir: general
          repos: |
            repoA
            repoB
            repoC
      - name: sync go assets
        uses: at-wat/assets-sync-action@v0
        with:
          root_dir: go
          repos: |
            repoA
            repoB
```

When we edit both `general` and `go` assets on a commit then push `master` branch, the two asset sync steps try to push `sync-assets-master` so that pull requests against `repoA` and `repoB` will conflict.

To avoid it, it would be nice for the asset sync action to have an option to specify head branch name like following.

```yaml
name: assets-sync
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync general assets
        uses: at-wat/assets-sync-action@v0
        with:
          root_dir: general
          branch: sync-general-assets # here
          repos: |
            repoA
            repoB
            repoC
      - name: sync go assets
        uses: at-wat/assets-sync-action@v0
        with:
          root_dir: go
          branch: sync-go-assets # here
          repos: |
            repoA
            repoB
```

**Comment by kamatama41** [comment]
or it might be better to add an option to specify multiple `root_dir`s like this:

```yaml
name: assets-sync
on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync general projects
        uses: at-wat/assets-sync-action@v0
        with:
          root_dirs: general
          repos: |
            repoC
      - name: sync go projeects
        uses: at-wat/assets-sync-action@v0
        with:
          root_dirs: |
            general
            go
          repos: |
            repoA
            repoB
```
