### ISSUE TITLE
Support assign reviewers

### ISSUE THREAD

**Issue by kamatama41** [at-wat/assets-sync-action#20]
Like this
```yaml
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        uses: at-wat/assets-sync-action@v0
        with:
          repos: |
            repoA
            repoB
          reviewers: |
            accountA
            accountB
```
