### ISSUE TITLE
Add option to select assets root directory

### ISSUE THREAD

**Issue by at-wat** [at-wat/assets-sync-action#7]
To support multiple sets of assets in one repository.
```yaml
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: sync
        uses: at-wat/assets-sync-action@v0
        with:
          repos: |
            owner/repo1
            owner/repo2
          github_token: ${{ secrets.GITHUB_TOKEN_REPO }}
          root_path: assets1
      - name: sync
        uses: at-wat/assets-sync-action@v0
        with:
          repos: |
            owner/repo3
          github_token: ${{ secrets.GITHUB_TOKEN_REPO }}
          root_path: assets2
```
